import gettext
_ = gettext.gettext
TABLES = [
    ('Es-Es-G0.utb', _('Spanish, computer (bidirect)'), 'both'),
    ('afr-za-g1.ctb', _('Afrikaans, uncontracted (bidirect)'), 'both'),
    ('afr-za-g2.ctb', _('Afrikaans, contracted (bidirect)'), 'both'),
    ('ar-ar-comp8.utb', _('Arabic, computer (bidirect)'), 'both'),
    ('ar-ar-g2.ctb', _('Arabic, contracted (bidirect)'), 'both'),
    ('ba.utb', _('Bashkir'), 'forward'),
    ('bel-comp.utb', _('Belarusian, computer (bidirect)'), 'both'),
    ('bel.utb', _('Belarusian'), 'forward'),
    ('chr-us-g1.ctb', _('Cherokee'), 'forward'),
    ('cop-eg-comp8.utb', _('Coptic, computer'), 'forward'),
    ('cs-comp8.utb', _('Czech, computer (bidirect)'), 'both'),
    ('cy-cy-g1.utb', _('Welsh, uncontracted (bidirect)'), 'both'),
    ('da-dk-g08.ctb', _('Danish, computer (bidirect)'), 'both'),
    ('da-dk-g16-lit.ctb', _('Danish, uncontracted, 6-dot'), 'forward'),
    ('da-dk-g16.ctb', _('Danish, uncontracted, 6-dot (bidirect)'), 'both'),
    ('da-dk-g18.ctb', _('Danish, uncontracted, 8-dot (bidirect)'), 'both'),
    ('da-dk-g26-lit.ctb', _('Danish, contracted, 6-dot'), 'forward'),
    ('da-dk-g26.ctb', _('Danish, contracted, 6-dot (bidirect)'), 'both'),
    ('da-dk-g26l-lit.ctb', _('Danish, partially contracted, 6-dot'), 'forward'),
    ('da-dk-g26l.ctb', _('Danish, partially contracted, 6-dot (bidirect)'), 'both'),
    ('da-dk-g28.ctb', _('Danish, contracted, 8-dot (bidirect)'), 'both'),
    ('da-dk-g28l.ctb', _('Danish, partially contracted, 8-dot (bidirect)'), 'both'),
    ('de-comp6.utb', _('German, computer, 6-dot (bidirect)'), 'both'),
    ('de-de-comp8.ctb', _('German, computer, 8-dot (bidirect)'), 'both'),
    ('de-g0-bidi.utb', _('German, uncontracted, back-translatable (bidirect)'), 'both'),
    ('de-g0.utb', _('German, uncontracted'), 'forward'),
    ('de-g1-bidi.ctb', _('German, partially contracted, back-translatable (bidirect)'), 'both'),
    ('de-g1.ctb', _('German, partially contracted'), 'forward'),
    ('de-g2.ctb', _('German, contracted'), 'forward'),
    ('el.ctb', _('Greek (bidirect)'), 'both'),
    ('en-gb-comp8.ctb', _('English, U.K., computer (bidirect)'), 'both'),
    ('en-gb-g1.utb', _('English, U.K., uncontracted'), 'forward'),
    ('en-nabcc.utb', _('English, U.S., computer, NABCC (bidirect)'), 'both'),
    ('en-ueb-g1.ctb', _('English, unified, uncontracted (bidirect)'), 'both'),
    ('en-ueb-g2.ctb', _('English, unified, contracted (bidirect)'), 'both'),
    ('en-us-comp6.ctb', _('English, U.S., computer, 6-dot (bidirect)'), 'both'),
    ('en-us-g1.ctb', _('English, U.S., uncontracted (bidirect)'), 'both'),
    ('eo-g1-x-system.ctb', _('Esperanto x-system (bidirect)'), 'both'),
    ('es-g2.ctb', _('Spanish, contracted'), 'forward'),
    ('fa-ir-comp8.ctb', _('Persian, computer (bidirect)'), 'both'),
    ('fa-ir-g1.utb', _('Persian'), 'forward'),
    ('fi-fi-8dot.ctb', _('Finnish, computer (bidirect)'), 'both'),
    ('fi.utb', _('Finnish'), 'forward'),
    ('fr-bfu-comp6.utb', _('French, uncontracted (bidirect)'), 'both'),
    ('fr-bfu-comp8.utb', _('French, computer (bidirect)'), 'both'),
    ('fr-bfu-g2.ctb', _('French, contracted (bidirect)'), 'both'),
    ('ga-g1.utb', _('Irish, uncontracted'), 'forward'),
    ('ga-g2.ctb', _('Irish, contracted (bidirect)'), 'both'),
    ('grc-international-en.utb', _('Greek, international, English'), 'forward'),
    ('haw-us-g1.ctb', _('Hawaiian (bidirect)'), 'both'),
    ('he-IL-comp8.utb', _('Hebrew, computer (bidirect)'), 'both'),
    ('he-IL.utb', _('Hebrew, Israel'), 'forward'),
    ('hu-hu-comp8.ctb', _('Hungarian, computer (bidirect)'), 'both'),
    ('hu-hu-g2.ctb', _('Hungarian, contracted (bidirect)'), 'both'),
    ('it-it-comp8.utb', _('Italian, computer (bidirect)'), 'both'),
    ('iu-ca-g1.ctb', _('Inuktitut'), 'forward'),
    ('ja-kantenji.utb', _('Japanese, Kantenji'), 'forward'),
    ('kk.utb', _('Kazakh'), 'forward'),
    ('ko-2006-g1.ctb', _('Korean, uncontracted, 2006 (bidirect)'), 'both'),
    ('ko-2006-g2.ctb', _('Korean, contracted, 2006'), 'forward'),
    ('ko-g1.ctb', _('Korean, uncontracted (bidirect)'), 'both'),
    ('ko-g2.ctb', _('Korean, contracted'), 'forward'),
    ('mao-nz-g1.ctb', _('Maori (bidirect)'), 'both'),
    ('mn-MN-g1.utb', _('Mongolian, uncontracted'), 'forward'),
    ('mn-MN-g2.ctb', _('Mongolian, contracted'), 'forward'),
    ('ms-my-g2.ctb', _('Malay'), 'forward'),
    ('nl-comp8.utb', _('Dutch, computer (bidirect)'), 'both'),
    ('no-no-8dot-fallback-6dot-g0.utb', _('Norwegian, uncontracted, 8-dot, 6-dot fallback'), 'forward'),
    ('no-no-8dot.utb', _('Norwegian, uncontracted, 8-dot (bidirect)'), 'both'),
    ('no-no-comp8.ctb', _('Norwegian, computer (bidirect)'), 'both'),
    ('no-no-g0.utb', _('Norwegian, uncontracted, 6-dot (bidirect)'), 'both'),
    ('no-no-g1.ctb', _('Norwegian, contracted, grade 1 (bidirect)'), 'both'),
    ('no-no-g2.ctb', _('Norwegian, contracted, grade 2 (bidirect)'), 'both'),
    ('nso-za-g1.utb', _('Sepedi, uncontracted (bidirect)'), 'both'),
    ('nso-za-g2.ctb', _('Sepedi, contracted (bidirect)'), 'both'),
    ('pl-pl-comp8.ctb', _('Polish, computer (bidirect)'), 'both'),
    ('pt-pt-comp8.ctb', _('Portuguese, computer (bidirect)'), 'both'),
    ('pt-pt-g1.utb', _('Portuguese, uncontracted (bidirect)'), 'both'),
    ('ru-compbrl.ctb', _('Russian, for program sources (bidirect)'), 'both'),
    ('ru-litbrl-detailed.utb', _('Russian, with capitals (bidirect)'), 'both'),
    ('ru-litbrl.ctb', _('Russian (bidirect)'), 'both'),
    ('ru-ru-g1.ctb', _('Russian, contracted'), 'forward'),
    ('ru.ctb', _('Russian, computer (bidirect)'), 'both'),
    ('sah.utb', _('Yakut'), 'forward'),
    ('sl-si-comp8.ctb', _('Slovenian, computer (bidirect)'), 'both'),
    ('sot-za-g1.ctb', _('Sesotho, uncontracted (bidirect)'), 'both'),
    ('sot-za-g2.ctb', _('Sesotho, contracted (bidirect)'), 'both'),
    ('sv-1989.ctb', _('Swedish, computer, 1989'), 'both.'),
    ('sv-1996.ctb', _('Swedish, computer, 1996 (bidirect)'), 'both'),
    ('ta-ta-g1.ctb', _('Tamil'), 'forward'),
    ('tsn-za-g1.ctb', _('Setswana, uncontracted (bidirect)'), 'both'),
    ('tsn-za-g2.ctb', _('Setswana, contracted (bidirect)'), 'both'),
    ('tt.utb', _('Tatar'), 'forward'),
    ('uk-comp.utb', _('Ukrainian, computer (bidirect)'), 'both'),
    ('uk.utb', _('Ukrainian'), 'forward'),
    ('ur-pk-g1.utb', _('Urdu, uncontracted (bidirect)'), 'both'),
    ('ur-pk-g2.ctb', _('Urdu, contracted (bidirect)'), 'both'),
    ('uz-g1.utb', _('Uzbek'), 'forward'),
    ('ve-za-g1.utb', _('Tshivenda, uncontracted (bidirect)'), 'both'),
    ('ve-za-g2.ctb', _('Tshivenda, contracted (bidirect)'), 'both'),
    ('vi-saigon-g1.ctb', _('Vietnamese, Saigon, contracted'), 'forward'),
    ('vi-vn-g0.utb', _('Vietnamese, uncontracted (bidirect)'), 'both'),
    ('vi-vn-g1.ctb', _('Vietnamese, partially contracted'), 'forward'),
    ('vi-vn-g2.ctb', _('Vietnamese, contracted'), 'forward'),
    ('vi.ctb', _('Vietnamese, computer (bidirect)'), 'both'),
    ('xh-za-g1.utb', _('isiXhosa, uncontracted (bidirect)'), 'both'),
    ('xh-za-g2.ctb', _('isiXhosa, contracted (bidirect)'), 'both'),
    ('zhcn-g1.ctb', _('Mandarin, mainland China, with tones'), 'forward'),
    ('zhcn-g2.ctb', _('Mandarin, mainland China, 2-cell (bidirect)'), 'both'),
    ('zu-za-g1.utb', _('isiZulu, uncontracted (bidirect)'), 'both'),
    ('zu-za-g2.ctb', _('isiZulu, contracted (bidirect)'), 'both'),
]
